# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# Pods for Firebase
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Corrected method name: install_all_flutter_pods
  install_all_flutter_pods File.dirname(File.realpath(__FILE__))
end

